server:
  port: 8081
  servlet:
    context-path: "/currency_search_api"

elasticsearch:
  url: localhost:9200

openExchangeRatesCurrencyNamesUri: "http://localhost:8082/open_exchange_rates_api/currency/currencies"