server:
  port: 8081
  servlet:
    context-path: "/currency_search_api"

elasticsearch:
  url: localhost:9200

alprkeskin:
  arbitrage:
    threshold: 5
  queues:
    to:
      currency: "search-to-currency"

openExchangeRatesCurrencyNamesUri: "http://localhost:8082/open_exchange_rates_api/currency/currencies"