server:
  port: 8081
  servlet:
    context-path: "/api"

elasticsearch:
  url: localhost:9200

alprkeskin:
  arbitrage:
    threshold: 5
  queues:
    to:
      currency: "search-to-currency"

feign-client:
  currency:
    name: "currency-service"
    url: "http://localhost:8082/api/currency"