server:
  port: 8082
  servlet:
    context-path: "/open_exchange_rates_api"

alprkeskin:
  arbitrage:
    rate: 0.51
  queues:
    from:
      search: "search-to-currency"
  consumed-urls:
    api: "https://openexchangerates.org/api/"

query-parameter:
  app_id: "8749ae82dbde4276a7554e13d03ad71e"

spring:
  data:
    mongodb:
      #authentication-database: admin
      #database: openExchangeServiceDatabase
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672

bananazura:
  spring:
    basePackage: "io.github.alprkeskin"
    aop:
      log:
        exception:
          aspect: true
        info:
          aspect: true
          printarguments: true