authenticate-endpoints:
  endpoints:
    - validUserType: ADMIN
      method: DELETE
      endpoint: "/api/auth/unregister"

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authenticationModule
          uri: http://localhost:8088/
          predicates:
            - Path=/api/auth/**
        - id: currencyEndpoints
          uri: http://localhost:8082
          predicates:
            - Path=/api/currency/**
        - id: searchEndpoints
          uri: http://localhost:8081
          predicates:
            - Path=/api/search/**

feign-client:
  authentication:
    name: "authentication-service"
    url: "http://auth-service:8088/api/auth/check"