authenticate-endpoints:
  endpoints:
    - validUserType: ADMIN
      method: DELETE
      endpoint: "/api/auth/unregister"
    - validUserType: CUSTOMER
      method: POST
      endpoint: "/api/wallet/deposit"
    - validUserType: CUSTOMER
      method: POST
      endpoint: "/api/wallet/withdraw"
    - validUserType: CUSTOMER
      method: GET
      endpoint: "/api/wallet/assets"

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:

      routes:
        - id: authenticationModule
          uri: http://localhost:8088/
          predicates:
            - Path=/api/auth/**
        - id: currencyEndpoints
          uri: http://localhost:8082
          predicates:
            - Path=/api/currency/**
        - id: searchEndpoints
          uri: http://localhost:8081
          predicates:
            - Path=/api/search/**
        - id: walletEndpoints
          uri: http://localhost:8083
          predicates:
            - Path=/api/wallet/**

feign-client:
  authentication:
    name: "authentication-service"
    url: "http://localhost:8088/api/auth/check"