server:
  servlet:
    context-path: "/api/auth"
  port: 8088
spring:
  application:
    name: "authentication-service"
  datasource:
    hikari:
      connectionTimeout: 20000
      maximum-pool-size: 5
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: update