server:
  port: 8083
  servlet:
    context-path: "/api"

spring:
  data:
    mongodb:
      #authentication-database: admin
      database: wallet_db
      port: 27017
      host: localhost

alprkeskin:
  queues:
    to:
      currency: "wallet-to-currency"